#1 Top Page 実装
Etsuwo/MogiQiita pull request #5
Opened 2021-05-28 08:48 UTC by Etsuwo

Top Pageの実装をしました．
APIに使用するURLなどの管理がかなり怪しいですが，実装していくうちに整理しようと思います．

主な処理流れ
1. ログインボタン押下
2. モーダル遷移でWebViewに遷移
3. OAuth認証を行う
4. リダイレクトを受けてWebViewを閉じる
5. APIを叩いてアクセストークンを取得する
6. 取得に成功したら，FeedPage（仮）に遷移，失敗したらアラートを表示

View以外のファイルについて
1. UserInfo.swift：ユーザの個人情報を扱う．現在はアクセストークンのみ．
2. Request.swift：通信周りを扱う．また，認証に必要になるclient_idとclient_secretについて，公開しない方が良い(?)と考えたので.envファイルを用意して読み込んでいます．

2021-05-31 00:44 UTC, mcz9mm commented
別途DMか何かで教えてください。
> UserInfo.swift：ユーザの個人情報を扱う．現在はアクセストークンのみ．
Request.swift：通信周りを扱う．また，認証に必要になるclient_idとclient_secretについて，公開しない方が良い(?)と考えたので.envファイルを用意して読み込んでいます．

2021-05-31 03:01 UTC, mcz9mm requested changes
レイアウト面はOKなのでコメント部分の修正お願いします

2021-05-31 03:01 UTC, mcz9mm commented on MogiQiita/TopPage/TopPageView.swift
> +                        NavigationLink(
ログイン後はトップ画面へ戻れないようにするか、presentで全画面モーダルで表示するようにしてください。

2021-05-31 03:31 UTC, Etsuwo commented on MogiQiita/UserInfo.swift
> +    var accessToken: String = ""
わかりました。
キーチェインを使って実装しようと思います。

2021-05-31 03:35 UTC, Etsuwo commented on MogiQiita/TopPage/TopPageView.swift
> +                        NavigationLink(
わかりました。
全画面モーダルにしてみます。

2021-05-31 14:42 UTC, Etsuwo commented
修正を行いました．

トークンの保存についてはKeyChainAccessのライブラリを使用し，主な動作は以下の通りです．
1. アプリ起動時にキーチェインからトークンを取得、取得できたらトップページから自動で遷移．
2. アプリ終了時にキーチェインにトークンを保存．

遷移方法については、fullCoverScreenを使用した全画面モーダルに変更しました．
また、フォントもgitの追跡対象に加えたので、podinstallと.envファイル加えるだけで動くと思います．

2021-06-01 01:44 UTC, mcz9mm approved these changes
LGTM

2021-06-01 01:45 UTC, mcz9mm commented
merge権限無いのでセルフマージで

2021-06-01 06:11 UTC, merged

2021-06-01 06:11 UTC, Etsuwo commented
ありがとうございます。
次回はmergeできるように設定しておきます。